; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "pragmat"
#define MyAppVersion "1.0"
#define MyAppPublisher "My Company, Inc."
#define MyAppURL "https://www.example.com/"
#define MyAppExeName "MyProg.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{EF5ACCC2-5347-49DE-8A48-9F096B6D9B02}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=C:\Users\Cheshire\Desktop\Новая папка
OutputBaseFilename=pragmat2_setup
SetupIconFile=D:\projects\ModBusMaster\icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Program Files (x86)\Inno Setup 6\Examples\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Cheshire\Desktop\deploy@Assistant\Assistant.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Cheshire\Desktop\deploy@Assistant\D3Dcompiler_47.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Cheshire\Desktop\deploy@Assistant\libEGL.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Cheshire\Desktop\deploy@Assistant\libgcc_s_seh-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Cheshire\Desktop\deploy@Assistant\libGLESv2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Cheshire\Desktop\deploy@Assistant\libstdc++-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Cheshire\Desktop\deploy@Assistant\libwinpthread-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Cheshire\Desktop\deploy@Assistant\opengl32sw.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Cheshire\Desktop\deploy@Assistant\Qt5Charts.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Cheshire\Desktop\deploy@Assistant\Qt5Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Cheshire\Desktop\deploy@Assistant\Qt5Gui.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Cheshire\Desktop\deploy@Assistant\Qt5Network.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Cheshire\Desktop\deploy@Assistant\Qt5Qml.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Cheshire\Desktop\deploy@Assistant\Qt5QmlModels.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Cheshire\Desktop\deploy@Assistant\Qt5QmlWorkerScript.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Cheshire\Desktop\deploy@Assistant\Qt5Quick.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Cheshire\Desktop\deploy@Assistant\Qt5QuickControls2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Cheshire\Desktop\deploy@Assistant\Qt5QuickTemplates2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Cheshire\Desktop\deploy@Assistant\Qt5RemoteObjects.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Cheshire\Desktop\deploy@Assistant\Qt5SerialBus.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Cheshire\Desktop\deploy@Assistant\Qt5SerialPort.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Cheshire\Desktop\deploy@Assistant\Qt5Svg.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Cheshire\Desktop\deploy@Assistant\Qt5Widgets.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

