; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Assiatant"
#define MyAppVersion "1.0"
#define MyAppPublisher "Vniizht, Inc."
#define MyAppURL "https://www.vniizht.ru/"
#define MyAppExeName "MyProg.exe"
#define MyAppAssocName "Pragmat File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{3DDC1884-4EA7-4A2A-9854-F578C1859450}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\Pragmat
ChangesAssociations=yes
DisableProgramGroupPage=yes
InfoBeforeFile=Pragmat
InfoAfterFile=Pragmat 1.0
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=C:\Users\Cheshire\Desktop
OutputBaseFilename=Assistant_setup
SetupIconFile=D:\projects\ModBusMaster\icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Program Files (x86)\Inno Setup 6\Examples\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\deploy\Assistant.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\deploy\D3Dcompiler_47.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\deploy\libEGL.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\deploy\libgcc_s_seh-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\deploy\libGLESv2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\deploy\libstdc++-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\deploy\libwinpthread-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\deploy\opengl32sw.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\deploy\Qt5Charts.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\deploy\Qt5Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\deploy\Qt5Gui.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\deploy\Qt5Network.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\deploy\Qt5Qml.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\deploy\Qt5QmlModels.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\deploy\Qt5QmlWorkerScript.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\deploy\Qt5Quick.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\deploy\Qt5QuickControls2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\deploy\Qt5QuickTemplates2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\deploy\Qt5RemoteObjects.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\deploy\Qt5SerialBus.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\deploy\Qt5SerialPort.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\deploy\Qt5Svg.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\deploy\Qt5Widgets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\deploy\bearer\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\deploy\canbus\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\deploy\iconengines\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\deploy\imageformats\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\deploy\qmltooling\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\deploy\Qt\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\deploy\QtCharts\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\deploy\QtGraphicalEffects\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\deploy\QtQml\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\deploy\QtQuick\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\deploy\QtQuick.2\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\deploy\translations\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\deploy\styles\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

